### PR TITLE
Added New Relic environment variables to README.md

### LINKED ISSUE #320: Add New Relic environment variables to README.md
**What is the problem?**

We introduced more variables for configuring Jarbas in #319, but they were not documented.

**How can this be addressed?**

Add these variables to the docs (so far, `README.md`) in the _Settings_ section.

### PR DESCRIPTION
**Pull request by nayeemnazmul**
fixes #320

### CODE REVIEW

**Comment by cuducos** [comment]
Many thanks, @nayeemnazmul : ) Looks good. Would you mind adding `NEW_RELIC_DEVELOPER_MODE` too, as it is suggested in `contrib/.env.sample`?

**Comment by nayeemnazmul** [comment]
Done! Please check @cuducos

**Comment by cuducos** [comment]
Great, many many thanks, @nayeemnazmul : )

**Comment by nayeemnazmul** [comment]
You are most welcome @cuducos 😄. I am actually learning how to contribute to open source projects. This was one of my baby steps. 😐

**Pull request merged**
